import { jsPDF } from "jspdf";
import { money, usdt } from "./desk";
import { getWalletDepositHoldUntil } from "./wallet";
import type { AdminActivityLog, CustomerUser, DeskOrder, WalletDeposit, WalletLedgerEntry, WalletWithdrawal } from "./types";

interface ReportInput {
  activityLogs: AdminActivityLog[];
  customers: CustomerUser[];
  deposits: WalletDeposit[];
  from: string;
  generatedBy: string;
  ledger: WalletLedgerEntry[];
  orders: DeskOrder[];
  to: string;
  withdrawals: WalletWithdrawal[];
}

const page = {
  margin: 14,
  width: 210,
  height: 297
};

export function downloadAdminReportPdf(input: ReportInput) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const customerByMobile = new Map(input.customers.map((customer) => [customer.mobile, customer]));
  let y = 18;

  const rangeLabel = `${formatDate(input.from)} to ${formatDate(input.to)}`;
  const fileRange = `${input.from}_to_${input.to}`;
  const totals = {
    orders: input.orders.length,
    buyOrders: input.orders.filter((order) => order.mode === "buy").length,
    sellOrders: input.orders.filter((order) => order.mode === "sell").length,
    orderUsdt: input.orders.reduce((sum, order) => sum + order.amount, 0),
    orderInr: input.orders.reduce((sum, order) => sum + order.inr, 0),
    depositUsdt: input.deposits.reduce((sum, deposit) => sum + deposit.amount, 0),
    withdrawalUsdt: input.withdrawals.reduce((sum, withdrawal) => sum + withdrawal.amount, 0)
  };

  drawTitle(doc, "COINVERA ADMIN REPORT", rangeLabel);
  y = 44;
  y = drawKeyValues(doc, y, [
    ["Generated by", input.generatedBy],
    ["Generated at", new Date().toLocaleString("en-IN")],
    ["Report period", rangeLabel],
    ["Total orders", String(totals.orders)],
    ["Buy / Sell orders", `${totals.buyOrders} / ${totals.sellOrders}`],
    ["Order USDT volume", usdt(totals.orderUsdt)],
    ["Order INR value", money(totals.orderInr)],
    ["Wallet deposits", `${input.deposits.length} entries, ${usdt(totals.depositUsdt)}`],
    ["Wallet withdrawals", `${input.withdrawals.length} entries, ${usdt(totals.withdrawalUsdt)}`]
  ]);

  y = drawSection(doc, y + 4, "Orders", input.orders, (order) => {
    const customer = customerByMobile.get(order.customerMobile || order.phone);
    return [
      ["Order ID", order.id],
      ["Type / Status", `${order.mode.toUpperCase()} / ${order.status}`],
      ["Created / Expires", `${formatDateTime(order.createdAt)} / ${order.expiresAt ? formatDateTime(order.expiresAt) : "Not set"}`],
      ["Customer", `${order.name} | ${order.phone}${customer?.email ? ` | ${customer.email}` : ""}`],
      ["Amount / Rate / INR", `${usdt(order.amount)} | ${money(order.rate)} per USDT | ${money(order.inr)}`],
      ["Network", order.network || "Not selected"],
      ["Wallet / TX", order.wallet || "Not added"],
      ["Payment", `${order.payment || "Not added"}${order.paymentMethod ? ` | ${order.paymentMethod}` : ""}${order.paymentReference ? ` | Ref: ${order.paymentReference}` : ""}`],
      ["Delivery", order.deliveryMethod || "external"],
      ["Proof", `Customer: ${order.paymentScreenshot ? "uploaded" : "not uploaded"} | Coinvera: ${order.adminProof ? "uploaded" : "not uploaded"}`],
      ["Assigned staff", `${order.assignedStaffName || "Unassigned"}${order.assignedStaffId ? ` (${order.assignedStaffId})` : ""}`],
      ["Confirmations", `Customer: ${order.customerConfirmed ? "yes" : "no"} | Admin: ${order.adminConfirmed ? "yes" : "no"}`],
      ["Chat messages", String(order.chat?.length || 0)]
    ];
  });

  y = drawSection(doc, y + 4, "Wallet Deposits", input.deposits, (deposit) => {
    const customer = customerByMobile.get(deposit.customerMobile);
    return [
      ["Deposit ID", deposit.id],
      ["Status", deposit.status],
      ["Customer", `${deposit.customerName} | ${deposit.customerMobile}${customer?.email ? ` | ${customer.email}` : ""}`],
      ["Amount / Network", `${usdt(deposit.amount)} | ${deposit.network}`],
      ["Coinvera wallet", deposit.walletAddress],
      ["Transaction hash", deposit.txHash],
      ["Created / Hold until", `${formatDateTime(deposit.createdAt)} / ${formatDateTime(getWalletDepositHoldUntil(deposit))}`],
      ["Verified / Rejected", `${deposit.verifiedAt ? formatDateTime(deposit.verifiedAt) : "No"} / ${deposit.rejectedAt ? formatDateTime(deposit.rejectedAt) : "No"}`],
      ["Staff", `${deposit.verifiedByStaffName || "Not handled"}${deposit.verifiedByStaffId ? ` (${deposit.verifiedByStaffId})` : ""}`],
      ["Admin note", deposit.adminNote || "None"]
    ];
  });

  y = drawSection(doc, y + 4, "Wallet Withdrawals / Direct Wallet Transfers", input.withdrawals, (withdrawal) => {
    const customer = customerByMobile.get(withdrawal.customerMobile);
    return [
      ["Withdrawal ID", withdrawal.id],
      ["Status", withdrawal.status],
      ["Customer", `${withdrawal.customerName} | ${withdrawal.customerMobile}${customer?.email ? ` | ${customer.email}` : ""}`],
      ["Amount / Network", `${usdt(withdrawal.amount)} | ${withdrawal.network}`],
      ["Receiving wallet", withdrawal.address],
      ["Created / Completed", `${formatDateTime(withdrawal.createdAt)} / ${withdrawal.completedAt ? formatDateTime(withdrawal.completedAt) : "Not completed"}`],
      ["Cancelled", withdrawal.cancelledAt ? formatDateTime(withdrawal.cancelledAt) : "No"],
      ["TX hash / Proof ref", withdrawal.txHash || "Not entered"],
      ["Handled by", `${withdrawal.handledByStaffName || "Not handled"}${withdrawal.handledByStaffId ? ` (${withdrawal.handledByStaffId})` : ""}`],
      ["Admin note", withdrawal.adminNote || "None"]
    ];
  });

  y = drawSection(doc, y + 4, "Wallet Ledger Movements", input.ledger, (entry) => {
    const customer = customerByMobile.get(entry.customerMobile);
    return [
      ["Ledger ID", entry.id],
      ["Date / Type", `${formatDateTime(entry.at)} / ${entry.type}`],
      ["Customer", `${entry.customerMobile}${customer?.fullName ? ` | ${customer.fullName}` : ""}${customer?.email ? ` | ${customer.email}` : ""}`],
      ["Amount", usdt(entry.amount)],
      ["Linked records", `Order: ${entry.orderId || "-"} | Deposit: ${entry.depositId || "-"} | Withdrawal: ${entry.withdrawalId || "-"}`],
      ["Note", entry.note]
    ];
  });

  drawSection(doc, y + 4, "Activity Log", input.activityLogs, (log) => [
    ["Log ID", log.id],
    ["Date", formatDateTime(log.at)],
    ["Staff", `${log.staffName} (${log.staffId}) - ${log.role}`],
    ["Action", log.action],
    ["Order", log.orderId || "System"],
    ["Detail", log.detail || "None"]
  ]);

  drawPageNumbers(doc);
  doc.save(`coinvera-report-${fileRange}.pdf`);
}

function drawTitle(doc: jsPDF, title: string, subtitle: string) {
  doc.setFillColor(0, 20, 17);
  doc.rect(0, 0, page.width, 34, "F");
  doc.setTextColor(0, 211, 149);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(title, page.margin, 16);
  doc.setTextColor(235, 255, 249);
  doc.setFontSize(10);
  doc.text(subtitle, page.margin, 25);
  doc.setTextColor(21, 32, 30);
}

function drawKeyValues(doc: jsPDF, y: number, rows: string[][]) {
  doc.setFontSize(9);
  rows.forEach(([label, value]) => {
    y = ensureSpace(doc, y, 8);
    doc.setFont("helvetica", "bold");
    doc.text(label, page.margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(String(value), 72, y);
    y += 6;
  });
  return y;
}

function drawSection<T>(doc: jsPDF, y: number, title: string, rows: T[], project: (row: T) => string[][]) {
  y = ensureSpace(doc, y, 18);
  doc.setFillColor(232, 246, 241);
  doc.rect(page.margin, y - 5, page.width - page.margin * 2, 9, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(0, 70, 60);
  doc.text(`${title} (${rows.length})`, page.margin + 2, y + 1);
  doc.setTextColor(21, 32, 30);
  y += 10;

  if (rows.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("No records found in this period.", page.margin, y);
    return y + 8;
  }

  rows.forEach((row, index) => {
    y = ensureSpace(doc, y, 16);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(`${index + 1}.`, page.margin, y);
    y += 4;
    project(row).forEach(([label, value]) => {
      const lines = doc.splitTextToSize(String(value || "-"), 118) as string[];
      y = ensureSpace(doc, y, Math.max(7, lines.length * 4 + 2));
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.text(label, page.margin + 5, y);
      doc.setFont("helvetica", "normal");
      doc.text(lines, 72, y);
      y += Math.max(5, lines.length * 4);
    });
    doc.setDrawColor(222, 232, 228);
    doc.line(page.margin, y + 1, page.width - page.margin, y + 1);
    y += 6;
  });

  return y;
}

function ensureSpace(doc: jsPDF, y: number, needed: number) {
  if (y + needed < page.height - 16) return y;
  doc.addPage();
  return 18;
}

function drawPageNumbers(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let index = 1; index <= pages; index += 1) {
    doc.setPage(index);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(98, 116, 110);
    doc.text(`Page ${index} of ${pages}`, page.width - page.margin, page.height - 8, { align: "right" });
    doc.setTextColor(21, 32, 30);
  }
}

function formatDate(value: string) {
  if (!value) return "All time";
  return new Date(`${value}T00:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

function formatDateTime(value?: string) {
  if (!value) return "Not set";
  return new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
}
